stages:
  - test_and_report

variables:
  ALLURE_SERVER: 'http://localhost:5050/api/allure'
  ALLURE_PROJECT_NAME: 'demo'
  POSTMAN_COLLECTION: 'Test/crear_usuarios/crear_usuarios.json'
  POSTMAN_DATA: 'Test/crear_usuarios/data.json'
  POSTMAN_ENVIRONMENT: Test/localhost.environment.json'

test_and_report:
  stage: test_and_report
  image: node:18-alpine
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'  # Se ejecuta en cada push/commit
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'  # También en merge requests
  before_script:
    # Instalar dependencias necesarias
    - apk --no-cache add curl
    - npm install -g newman newman-reporter-allure
  script:
    - echo "Ejecutando tests con Newman y generando reportes Allure..."
    - newman run Test/crear_usuarios/crear_usuarios.json -d Test/crear_usuarios/data.json -e $POSTMAN_ENVIRONMENT --reporters cli,allure --reporter-allure-export ./allure-results
    - if [ ! -d allure-results ] || [ -z "$(ls -A allure-results/)" ]; then echo "No se encontraron resultados en allure-results/" && exit 1; fi
    - echo "Enviando resultados a Allure Server..."
    - curl -X POST "$ALLURE_SERVER/send-results?project_id=$ALLURE_PROJECT_NAME&force_project_creation=true" $(find allure-results -type f -exec echo -n "-F files[]=@{} " \;)
    - echo "Generando reporte en Allure Server..."
    - curl -X GET "$ALLURE_SERVER/generate-report?project_id=$ALLURE_PROJECT_NAME"
    - echo "✅ Tests completados y reporte generado en Allure Server"
    - echo "📊 Reporte disponible en http://localhost:5050/allure-docker-service-ui/projects/$ALLURE_PROJECT_NAME/reports/latest"

  artifacts:
    paths:
      - allure-results/
    when: always
    expire_in: 1 week
  
  # Permitir que el job falle sin afectar el pipeline si es necesario
  # allow_failure: true