# Generated by Django 5.2.5 on 2025-08-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20250818_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Tarjeta de Crédito'), ('debit_card', 'Tarjeta de Débito'), ('paypal', 'PayPal'), ('bank_transfer', 'Transferencia Bancaria'), ('cash_on_delivery', 'Pago Contra Entrega')], default='credit_card', max_length=20),
        ),
    ]
