name: CI Testing con Newman y Allure

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_and_report:
    runs-on: ubuntu-latest

    env:
      POSTMAN_COLLECTION: "TEST/CasoRegistrarUsuarios/RegistrarUsuarios.json"
      POSTMAN_DATA: "TEST/CasoRegistrarUsuarios/data.json"
      POSTMAN_ENVIRONMENT: "TEST/localhost_environment.json"

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Instalar dependencias necesarias
        run: |
          sudo apt-get update && sudo apt-get install -y curl unzip
          npm install -g newman newman-reporter-allure allure-commandline --save-dev

      - name: Ejecutar tests con Newman
        run: |
          echo "Ejecutando tests con Newman y generando reportes Allure..."
          newman run $POSTMAN_COLLECTION -d $POSTMAN_DATA -e $POSTMAN_ENVIRONMENT --reporters cli,allure --reporter-allure-export ./allure-results
          if [ ! -d allure-results ] || [ -z "$(ls -A allure-results/)" ]; then echo "❌ No se encontraron resultados en allure-results/" && exit 1; fi

      - name: Generar reporte HTML de Allure
        run: |
          echo "Generando reporte HTML de Allure..."
          allure generate allure-results --clean -o allure-report

      - name: Subir resultados de Allure como artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/

      - name: Subir reporte HTML como artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/
